로그인, 회원가입 기능 구현
JoberChipFrappuccino/joberchip-be-demo pull request #39
Opened 2023-09-20 08:11 UTC by nyeJiiii

resolve #35 

**로그인, 회원가입 기능 구현**

1. validation 의존성 추가
2. auth 모듈에 ApiResponse 복사
3. DTO 생성 (UserRequest, UserResponse)
4. 회원가입 기능
 - @ Valid (@ NotEmpty설정)
 - password encoding
5. 로그인 기능
 - @ Valid (@ NotEmpty설정)
 - 로그인 성공시 header에 JWT 발급

Exception 처리나 username 중복 검사같은 로직은 제외하고 일단 최소한의 기능으로만 구현해두었습니다.  

</br>

**JWT 인증 테스트**

`localhost:8081/login` 으로 로그인 한 후 header에 발급된 토큰으로 `localhost:8081/user` 접속가능

2023-09-20 12:10 UTC, gdtknight approved these changes

2023-09-20 12:10 UTC, gdtknight commented on api/auth-v1/src/main/java/kr/joberchip/auth/v1/controller/UserController.java
> +        User athurizedUser = userService.login(loginUser);
`userService` 에서 `User` Entity 를 직접 리턴하기 보단 토큰 생성까지 완료한 후에 토큰을 반환하는 것이 더 좋을 것 같아요 !

`Entity` 는 생성 이후에 영속성 컨텍스트에서 지속적으로 관리되고 있기 때문에 최대한 노출되지 않도록 하는 것이 좋습니다.

 서비스 레이어에서 컨트롤러로 `Entity`를 직접 반환하기보단 서비스 레이어에서 작업을 완료한 후 필요한 부분들만 별도의 DTO로 (현재 같은 경우에는 최종 생성된 토큰) 만들어서 전달하는 것이 좋습니다 !

2023-09-20 12:10 UTC, gdtknight commented on api/auth-v1/src/main/java/kr/joberchip/auth/v1/controller/UserController.java
> +        return ResponseEntity.ok().body(ApiResponse.success("회원가입 성공"));
응답에 메세지가 포함되어 있네요 !

프론트에서도 적절하게 처리하실 수 있도록 API 명세도 함께 업데이트 해주시면 좋을 것 같습니다 !

2023-09-20 15:14 UTC, gdtknight requested changes
고생하셨습니당 👍🏻

서비스에서 컨트롤러로 `User` 엔티티를 반환하는 부분만 수정 반영 부탁드립니다 ~

2023-09-21 04:54 UTC, nyeJiiii commented
상기 내용 반영 완

2023-09-21 05:06 UTC, gdtknight submitted a review, later dismissed
확인 완료 !

2023-09-21 05:07 UTC, gdtknight approved these changes

2023-09-21 05:07 UTC, merged